### ISSUE TITLE
make serialized epub a valid epub3

### ISSUE THREAD

**Issue by reedstrm** [openstax/cnx-epub#104]
Make the epub a valid epub3 doc, as per `epubcheck` validator. 
Known issues:
 1. manifest includes duplicate items
 2. items do not have ids
 3. spine element is missing (needs item ids)
 4. toc not correctly formatted

**Comment by philschatz** [comment]
And from #106 : We should probably reformat the metadata consistently (when to store values in attributes and when to store them in text nodes)

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
